# Generated by Django 3.1.4 on 2020-12-17 02:21

import apps.profiles.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader_Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(default='default.jpg', upload_to=apps.profiles.models.reader_photo_path)),
                ('password', models.CharField(max_length=200)),
                ('social_media_platform', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('PT', 'Pintrest'), ('TB', 'Tmblr')], default='FB', max_length=30)),
                ('social_media_handles', models.CharField(default='@Username', max_length=50)),
            ],
            options={
                'verbose_name': 'Reader Profile',
                'verbose_name_plural': 'Reader Profiles',
            },
        ),
        migrations.CreateModel(
            name='Contributor_Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(default='default.jpg', upload_to=apps.profiles.models.contributor_photo_path)),
                ('password', models.CharField(max_length=200)),
                ('social_media_platform', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('PT', 'Pintrest'), ('TB', 'Tumblr')], default='FB', max_length=50)),
                ('social_media_handles', models.CharField(max_length=50)),
                ('blog_post', models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Contributor Profile',
                'verbose_name_plural': 'Contributor Profiles',
            },
        ),
    ]
