# Generated by Django 3.1.4 on 2020-12-16 22:57

import apps.profiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.FileField(default='default.jpg', upload_to=apps.profiles.models.reader_photo_path)),
                ('Password', models.CharField(max_length=200)),
                ('Social_media_platform', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('PT', 'Pintrest'), ('TB', 'Tmblr')], default='FB', max_length=30)),
                ('Social_media_handles', models.CharField(default='@Username', max_length=50)),
            ],
            options={
                'verbose_name': 'Reader Profile',
                'verbose_name_plural': 'Reader Profiles',
            },
        ),
        migrations.CreateModel(
            name='Contributor_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_number', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('Image', models.FileField(default='default.jpg', upload_to=apps.profiles.models.contributor_photo_path)),
                ('Password', models.CharField(max_length=200)),
                ('Social_media_platform', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('PT', 'Pintrest'), ('TB', 'Tumblr')], default='FB', max_length=50)),
                ('Social_media_handles', models.CharField(default='@Username', max_length=50)),
                ('blog_post', models.ForeignKey(max_length=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Contributor Profile',
                'verbose_name_plural': 'Contributor Profiles',
            },
        ),
    ]
