# Generated by Django 3.1.4 on 2020-12-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201216_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor_profile',
            name='Phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='contributor_profile',
            name='Social_media_handles',
            field=models.CharField(max_length=50),
        ),
    ]
