# Generated by Django 3.1.4 on 2020-12-17 03:35

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201217_0312'),
        ('profiles', '0002_auto_20201217_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor_profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='reader_profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reader_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reader_profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='contributor_profile',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to=apps.profiles.models.contributor_photo_path),
        ),
        migrations.AlterField(
            model_name='reader_profile',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to=apps.profiles.models.reader_photo_path),
        ),
    ]
