# Generated by Django 3.1.4 on 2020-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201216_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor_profile',
            name='active',
        ),
        migrations.AddField(
            model_name='contributor_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
