# Generated by Django 3.1.4 on 2020-12-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201216_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Social_media_handles',
            new_name='social_media_handles',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Social_media_platform',
            new_name='social_media_platform',
        ),
        migrations.RenameField(
            model_name='contributor_profile',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Social_media_handles',
            new_name='social_media_handles',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Social_media_platform',
            new_name='social_media_platform',
        ),
        migrations.RenameField(
            model_name='reader_profile',
            old_name='Username',
            new_name='username',
        ),
    ]
