# Generated by Django 3.1.4 on 2020-12-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201217_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Post Category', 'verbose_name_plural': 'Blog Post Categories'},
        ),
    ]
