# Generated by Django 3.1.4 on 2020-12-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=40),
        ),
    ]
