# Generated by Django 3.1.4 on 2020-12-17 02:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20201217_0221'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.FileField(default='default_post.jpg', upload_to='media')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.FileField(default='default_post.jpg', upload_to='media')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit')], default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('contributors', models.ManyToManyField(to='profiles.Contributor_Profile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='magazine.issue')),
            ],
            options={
                'verbose_name': 'Issue Content',
                'verbose_name_plural': 'Issue Contents',
                'ordering': ['created_on'],
            },
        ),
    ]
