# Generated by Django 3.1.4 on 2020-12-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Content', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='profiles.contributor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Content', models.TextField()),
                ('Category', models.CharField(max_length=200)),
                ('Image', models.FileField(default='default_post.jpg', upload_to='media')),
                ('Slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit')], default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.contributor_profile')),
            ],
            options={
                'ordering': ['-Created_on'],
            },
        ),
    ]
