# Generated by Django 3.1.4 on 2020-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201216_2327'),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='contributor',
        ),
        migrations.AddField(
            model_name='issue',
            name='contributors',
            field=models.ManyToManyField(to='profiles.Contributor_Profile'),
        ),
    ]
