# Generated by Django 3.1.4 on 2020-12-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20201217_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='issue_content',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
