# Generated by Django 3.1.4 on 2020-12-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20201220_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.issue'),
        ),
    ]
