# Generated by Django 3.1.4 on 2020-12-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20201217_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue_content',
            options={'ordering': ['-created_on'], 'verbose_name': 'Issue Content', 'verbose_name_plural': 'Issue Contents'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='content',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='contributors',
        ),
    ]
