# Generated by Django 3.1.4 on 2020-12-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201216_2327'),
        ('magazine', '0005_auto_20201217_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.FileField(default='default_post.jpg', upload_to='media')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit')], default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(to='profiles.Contributor_Profile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='magazine.issue')),
            ],
            options={
                'verbose_name': 'Issue Content',
                'verbose_name_plural': 'Issue Contents',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Issue_Content',
        ),
    ]
