# Generated by Django 3.1.4 on 2020-12-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201217_0335'),
        ('blog', '0004_auto_20201220_1103'),
        ('magazine', '0006_auto_20201220_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='profiles.Contributor_Profile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='media'),
        ),
    ]
