# Generated by Django 3.1.4 on 2020-12-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201217_0018'),
        ('magazine', '0006_auto_20201217_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created_on'], 'verbose_name': 'Issue Content', 'verbose_name_plural': 'Issue Contents'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['published_date']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
